Image_Processing/urls.py
from django.urls import path
from .import views

app_name = "Image_Processing"

urlpatterns = [
    path('', views.process, name="pocess" )
]

blog/urls.py
from .import views
from django.urls import path

app_name = "blog"

urlpatterns = [
    path("", views.blog_list, name = "blog"),
    path("blog/<int:id>", views.blog_det, name = "blog_detail")
]

flower/urls.py
from .import views
from django.urls import path

app_name = "flower"

urlpatterns = [
    path("", views.flower_list, name = "flower_list"),
    path("flowers/", views.all_flowers, name = "all_flowers"),
    path("<int:id>", views.flower_des, name = "detail"),
    path("search/", views.search, name = "search"),
    path('all/', views.decoration, name='all_models')
]
    

goldoon/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('flower.urls')),
    # path('',  include('blog.urls')),
    path('alli/', views.all_models, name='all_models'),
    path('processing/',  include('Image_Processing.urls')),
    path('blog/',  include('blog.urls'))
]
urlpatterns += static (settings.STATIC_URL , document_root=settings.STATIC_ROOT )
urlpatterns += static (settings.MEDIA_URL , document_root=settings.MEDIA_ROOT )

Image_Processing/models.py
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.
class processing(models.Model):
    
    photo = models.ImageField(_("تصویر گل"), upload_to='process/')

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.translation import gettext as _

# Create your models here.

class blog(models.Model):
    title = models.CharField(_("عنوان"), max_length=50)
    description = models.CharField (_("توضیحات"), max_length=100)
    context = models.TextField("متن")
    image = models.ImageField(_("تصویر"), upload_to="blogs/", blank= True, null= True)
    created_at = models.DateTimeField(_("زمان انتشار"), default=timezone.now)
    author = models.ForeignKey(User, verbose_name=_("نویسنده"), on_delete=models.CASCADE, blank=True, null= True)

    category = models.ForeignKey("category", verbose_name=_("دسته بندی"), on_delete=models.CASCADE, related_name = "blog", blank=True, null= True)

    def __str__(self):
        return self.title

class category(models.Model):
    title = models.CharField(_("عنوان"),max_length=20)
    slug = models.SlugField(_("عنوان لاتین"),max_length=30)
    published_at = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.title

    

flower/models.py
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.
class flower(models.Model):
    EN_name = models.CharField(max_length=70, default="unknown")
    name = models.CharField(max_length=50)
    description = models.TextField(_("توضیحات"), max_length=10000)
    care = models.TextField(_("شیوه نگهداری"), max_length=10000, default="")
    water_requirement = models.CharField(max_length=130, default="")
    suitable_weather = models.CharField(max_length=130, default="")
    photo = models.ImageField(upload_to='flower/')
    flower_type = [
        ("apartment", "آپارتمانی"),
        ("garden", "باغچه ای"),
        ("ornamental", "زینتی")
    ]
    type_flower = models.CharField(_("نوع گل"), choices = flower_type, default= "garden", max_length= 50)

    def __str__(self):
        return self.name

Image_Processing/forms.py
from django import forms
from .models import processing
from django.utils.translation import gettext as _


class Processing_form(forms.ModelForm):
    photo = forms.ImageField(label=_("تصویر گل"), required=True, widget=forms.FileInput(attrs={'accept': 'image/*'}))

    class Meta:
        model = processing
        fields = "__all__"

Image_Processing/views.py
from django.shortcuts import render
from .forms import Processing_form
from flower.models import flower
from .utils.image_processor import classify_flower

    
# Create your views here.
def process(request):
    processing = Processing_form()
    if request.method == "POST":
        processing = Processing_form(request.POST, request.FILES)
        image = request.FILES.get('photo')
        result = classify_flower(image)
        print(result)

        Flower_detected = flower.objects.get(name=result)
        context = {
            'flower': Flower_detected
        }
        return render(request, 'flower/flowerdetail.html', context)
        return render(request, 'Image_Processing/result.html', {'result': result, 'flower': flower})
        # return render(request, 'Image_Processing/result.html', {'result': result})  # نمایش صفحه نتیجه به کاربر

    else:
        print(processing.errors)
        processing = Processing_form()
    
    context = {
        "form" : processing
    }

    return render(request, "Image_Processing/processingPage.html", context)

blog/views.py
from django.shortcuts import render
from .models import blog, category

# Create your views here.
def blog_list(request):
    blog_list = blog.objects.all()
    category_list = category.objects.all()
    context = {
        "blogs" : blog_list,
        "categories" : category_list
    }
    return render (request, "blog/blogpage.html" , context)

def blog_det(request , id):
    blog_detail = blog.objects.get(id = id)
    Recents = blog.objects.all().order_by("-created_at")[:10]
    context = {
        "blog" : blog_detail,
        "recents" : Recents,
         
    }
    return render(request, "blog/blog_detail.html", context)

flower/views.py
from django.shortcuts import render
from .models import flower
from blog.models import blog


# Create your views here.
def flower_list(request):
    flower_list = flower.objects.all()[:6]
    context = {
        "flowers" : flower_list
    }
    return render (request, "flower/HomePage.html" , context)

def all_flowers(request):
    all_flowers = flower.objects.all()
    context = {
        "flowers" : all_flowers
    }
    return render (request, "flower/FlowersPage.html" , context)

def flower_des(request , id):
    flower_detail = flower.objects.get(id = id)
    context = {
        "flower" : flower_detail
    }
    return render(request, "flower/flowerdetail.html", context)

def search(request):
    if request.method == "GET":
        q =request.GET.get("search")
    flower_list = flower.objects.filter(name__icontains=q)
    return render(request, "flower/searchresult.html" , {"flower_list": flower_list})



def decoration(request):
    model1_objects = flower.objects.all()
    model2_objects = blog.objects.all()
    return render(request, 'all.html', {'model1_objects': model1_objects, 'model2_objects': model2_objects})

goldoon/views.py
from django.shortcuts import render
from flower.models import flower
from blog.models import blog

def all_models(request):
    model1_objects = flower.objects.all()
    model2_objects = blog.objects.all()
    return render(request, 'main/all.html', {'model1_objects': model1_objects, 'model2_objects': model2_objects})

Image_Processing/templates/Image_Processing/processingPage.html
{% extends "Base.html" %}

{% block content %}


<div class="process-page">
    <div class="container process-form">
        <img id="previewImage" src="#" alt="پیش نمایش تصویر انتخابی">
        <form method="POST" action="" enctype="multipart/form-data" class="d-flex flex-column" onsubmit="return checkFile()">
            {% csrf_token %}
            <input type="file" id="fileInput" onchange="showImage(event)" name = "photo">
            <button type="submit" class="mt-3 sub-pic btn btn-info"> ارسال </button>

        </form>

    </div>
</div>

{% comment %} 
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <button type="submit"> ارسال </button>

</form> {% endcomment %}
{% endblock content %}

Image_Processing/templates/Image_Processing/result.html
{{ result }}


<h1>نتیجه:</h1>
   <p>اسم گل: {{ result }}</p>
   {% if flower %}
     <p>جزئیات گل:</p>
     <ul>
       <li>نام: {{ flower.name }}</li>
       <li>توضیحات: {{ flower.description }}</li>
       <!-- سایر ویژگی های گل -->
     </ul>
   {% else %}
     <p>گل مورد نظر یافت نشد.</p>
   {% endif %}

   

blog/templates/blog/blog_detail.html
{% extends "Base.html" %}

{{blog}}


{% block content %}

<section>
    <div class="container">
        <div class="row">
            <div class="col-4">
                <div class="Recent-Post p-4">
                    <h5 class="text-center">
                        مطالب اخیر
                    </h5>
                    <ul>
                        {% for blog in recents %}
                        <a href="{% url 'blog:blog_detail' blog.id %}">
                            <li class="mb-2"> {{blog.title}} </li>
                        </a>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-8">
                <div class="detail">
                    <h4 class="text-center"> {{blog.title}} </h4>
                    <div class="date-time"> {{blog.created_at | date}} </div>
                    <p class="mt-4 text-muted">
                        {{blog.description}}
                    </p>
                    <p>
                        {{blog.context}}
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

blog/templates/blog/blogpage.html
{% extends 'Base.html' %}
{% load static %}

{% block content %}


<!-- header -->
<section>
    <header>

        <div class="header text-center mt-4 p-0">
            <div class="web-header m-0 p-0">
                <img src="{% static 'assets/header-web.png' %}" class="img-fluid web-img">
                <div class="content-header">
                    <h1 class="web-title-header">
                        اینجا مکان نوشتن تایتل است
                    </h1>
                    <p class="web-para-header"> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vitae
                        culpa tempore quo. Blanditiis, labore amet.</p>
                    <div class="search-web">
                        <form action="{% url 'flower:search' %}" class="p-0 m-0" method="GET">
                            <input type="search" name="search" class="web-search-header">
                            <button type="submit"  class=" btn btn-info search-button-header"><i class="fas fa-search"></i></button>
                        </form> 
                        
                    </div>
                </div>
            </div>
        </div>


    </header>
</section>
<!-- end header -->


<section>
    <div class="bg-pop">
        <div class="row popular-box d-flex justify-content-center align-items-end">
            <div class="col-3 ">
                <h2>Shop Plant</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
            </div>
            <div class="col-3">
                <div class="row p-0 m-0 d-flex justify-content-center align-items-end">
                    <div class="col-7 p-0 m-0">
                        <img src="{% static 'assets/1.png' %}" class="d-inline img-fluid">
                    </div>
                    <div class="col-5 p-0 m-0">
                        <p>Lorem, ipsum.</p>
                        <p>Lorem ipsum dolor sit.</p>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <div class="row p-0 m-0 d-flex justify-content-center align-items-end">
                    <div class="col-7 p-0 m-0">
                        <img src="{% static 'assets/2.png' %}" class="d-inline img-fluid">
                    </div>
                    <div class="col-5 p-0 m-0">
                        <p>Lorem, ipsum.</p>
                        <p>Lorem ipsum dolor sit.</p>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <div class="row p-0 m-0 d-flex justify-content-center align-items-end">
                    <div class="col-7 p-0 m-0">
                        <img src="{% static 'assets/3.png' %}" class="d-inline img-fluid">
                    </div>
                    <div class="col-5 p-0 m-0">
                        <p>Lorem, ipsum.</p>
                        <p>Lorem ipsum dolor sit.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>





<!-- Popular plant -->
<section>
    <div class="row popular d-flex align-items-center">
        <div class="col-3">
            <h4 class="fw-bold pop-title">
                گیاهان محبوب
            </h4>
            <p class="des-popular mt-4">
                آنچه دیگران دوست دارند را ببینید
            </p>
            <button class="mt-4 btn btn-info btn-popular d-flex align-items-center justify-content-center">
                بیشتر
                <i class="fas fa-angle-double-left mx-1"></i>
            </button>
        </div>
        <div class="col-3">
            <div class="popular-card">
                <img src="{% static 'assets/galina-n-miziNqvJx5M-unsplash.jpg' %}" class="pop-img img-fluid">
                <div class="footer-card d-flex flex-column justify-content-start align-items-center">
                    <p class="grouping mt-2">دسته بندی گیاه</p>
                    <h5 class="pop-plant-name">نام گیاه</h5>
                    <span class="read-more">اطلاعات بیشتر</span>
                    <span class="Square"></span>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="popular-card">
                <img src="{% static 'assets/kara-eads-EbLX7oRo4vI-unsplash.jpg' %}" class="pop-img img-fluid">
                <div class="footer-card d-flex flex-column justify-content-start align-items-center">
                    <p class="grouping mt-2">دسته بندی گیاه</p>
                    <h5 class="pop-plant-name">نام گیاه</h5>
                    <span class="read-more">اطلاعات بیشتر</span>
                    <span class="Square"></span>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="popular-card">
                <img src="{% static 'assets/toa-heftiba-W1yjvf5idqA-unsplash.jpg' %}" class="pop-img img-fluid">
                <div class="footer-card d-flex flex-column justify-content-start align-items-center">
                    <p class="grouping mt-2">دسته بندی گیاه</p>
                    <h5 class="pop-plant-name">نام گیاه</h5>
                    <span class="read-more">اطلاعات بیشتر</span>
                    <span class="Square"></span>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Popular plant -->




<!-- weblogs sec -->

<section>
    <div class="container wbs text-center">
        <div class="title-section">
            <h3 class="title-weblog-section">
                فهرست مطالب
                <span class="poly"> </span>
            </h3>
        </div>



        <div class="row">

            <div class="col-3 categories-list">
                <ul>
                    <li class="category-title active" data-id="0">
                        همه
                    </li>
                    {% for category in categories %}
                    <li class="category-title" data-id="{{ category.id }}">
                        {{ category.title }}
                    </li>
                    {% endfor %}
                </ul>
            </div>

            <div class="col-9 blog-list">
                
                    {% for blog in blogs %}
                    <a href="{% url 'blog:blog_detail' blog.id %}">
                        <div class="blog row w-100  bg-white" data-category-id="{{ blog.category.id }}"
                            style="display: flex;">
                            <div class="col-3 text-center title-blog" data-hover="دیدن مطلب...">
                                {{ blog.title }}
                                <span class="jk"> </span>
                            </div>
                            <div class="col-6 description-blog">
                                <p>
                                    {{ blog.description }}
                                </p>
                            </div>
                            <div class="col-3 bg-info p-0 img-blog">
                                <img src="{{ blog.image.url }}" alt="" class="img-fluid">

                            </div>
                        </div>
                    </a>

                    {% endfor %}
                
            </div>
        </div>
    </div>
</section>








{% endblock content %}

flower/templates/flower/FlowersPage.html
{% extends 'Base.html' %}
{% load static %}


{% block content %}

<!-- flower page -->
<section>
    <div class="container">
        <div class="filter mb-4">
            <button type="button" class="btn btn-success all">همه</button>
            <button type="button" class="btn btn-success apartment">آپارتمانی</button>
            <button type="button" class="btn btn-success garden">باغچه ای</button>
            <button type="button" class="btn btn-success ornamental">زینتی</button>

        </div>
        <div class="row">
            {% for flower in flowers %}
            <div class="col-3">
                <a href="{% url 'flower:detail' flower.id %}">
                    <div class="flower-box {{flower.type_flower}} my-2">
                        <div class="image">
                            <img src="{{ flower.photo.url }}" class="object-fit-cover img-fluid w-100 h-100" alt="">
                        </div>
                        <div class="content">
                            <div class="name">
                                {{ flower.name }}
                            </div>
                            <div class="type">
                                {{ flower.get_type_flower_display }}
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}

        </div>
    </div>



    {% endblock %}


    <div class="aaaa">

    </div>





    <!-- bootstrap js -->
    <script src="js/bootstrap.bundle.min.js"></script>
    <!-- font awesome -->
    <script src="https://kit.fontawesome.com/8722263165.js" crossorigin="anonymous"></script>
    <script src="js/all.min.js"></script>
    <!-- script -->
    <script src="{% static 'js/FlowerPage.js' %}"></script>

    {% comment %} <script src="js/FlowerPage.js"></script> {% endcomment %}
    </body>

    </html>

flower/templates/flower/flowerdetail.html
{% extends 'Base.html' %}
{% load static %}

{% block content %}

    <!-- flower information section -->

    <section>
        

        <div class="container flower d-flex flex-column align-items-center">
            <H2 class="text-center mb-4">
                {{flower.name}}
                <span class="poly"> </span>

            </H2>
            <div class="row">
                <div class="col-4">
                    <div class="maintenance inf-box">
                        <!-- title -->
                        <div class="title">
                            <h5>
                                شیوه نگهداری
                            </h5>
                        </div>
                        <!-- end title -->
                        <div class="inf-content">
                            <p>
                                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Laborum commodi placeat
                                quisquam
                                culpa quam voluptatibus aliquam recusandae reprehenderit modi, inventore sapiente quasi
                                explicabo itaque dolorum velit repellat facere ullam dolore, aspernatur vero maiores
                                temporibus eos ipsa! Amet totam deleniti mollitia iusto? Aliquam ea consequuntur nostrum
                                recusandae dolorum quas animi facere.
                            </p>
                            <div class="jk"></div>
                            <div class="Short-information">
                                <div class="water mb-2">
                                    <span>
                                        میزان آب مورد نیاز:
                                    </span>
                                </div>
                                <div class="weather">
                                    <span>
                                        آب و هوای مناسب:
                                    </span>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="col-5">
                    <div class="introduction  inf-box">
                        <!-- title -->
                        <div class="title">
                            <h5>
                                معرفی
                            </h5>
                        </div>
                        <!-- end title -->
                        <p class="inf-content">
                            {{ flower.description }}
                        </p>
                    </div>
                </div>
                <div class="col-3">
                    <div class="flower-image inf-photo">
                        <img src="{{ flower.photo.url }}" class="img-fluid" alt="">


                    </div>
                </div>
            </div>
        </div>

    </section>



{% endblock content %}

flower/templates/flower/searchresult.html
{% extends 'Base.html' %}


{% block content %}

<!-- flower page -->
<section>
    <div class="container">
        <div class="filter mb-4">
            <h3>نتایج جستجو</h3>
        </div>
        <div class="row">
            {% if flower_list %}
            {% for flower in flower_list %}
            <div class="col-3">
                <a href="{% url 'flower:detail' flower.id %}">
                    <div class="flower-box {{flower.type_flower}} my-2">
                        <div class="image">
                            <img src="{{ flower.photo.url }}" class="object-fit-cover img-fluid w-100 h-100" alt="">
                        </div>
                        <div class="content">
                            <div class="name">
                                {{ flower.name }}
                            </div>
                            <div class="type">
                                {{ flower.get_type_flower_display }}
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
            {% else %}
            <p class="font"> گل موردنظر یافت نشد. </p>
            {% endif %}

        </div>
    </div>



    {% endblock %}


    <div class="aaaa">

    </div>





    <!-- bootstrap js -->
    <script src="js/bootstrap.bundle.min.js"></script>
    <!-- font awesome -->
    <script src="https://kit.fontawesome.com/8722263165.js" crossorigin="anonymous"></script>
    <script src="js/all.min.js"></script>
    <!-- script -->
    <script src="js/FlowerPage.js"></script>
    </body>

    </html>

goldoon/templates/main/all.html
{% for flower in model1_objects %}
    <h3>{{ flower.name }}</h3>
    <!-- display other fields of Model1 -->
{% endfor %}

{% for blog in model2_objects %}
    <h3>{{ blog.title }}</h3>
    <!-- display other fields of Model2 -->
{% endfor %}

templates/Base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- BootStrap -->
    <link rel="stylesheet" href="{% static 'style/bootstrap.rtl.min.css' %}">
    <!-- main style -->
    <link rel="stylesheet" href="{% static 'style/HomePage.css' %}">
    <link rel="stylesheet" href="{% static 'style/flowerdetail.css' %}">
    <link rel="stylesheet" href="{% static 'style/webpage.css' %}">
    <link rel="stylesheet" href="{% static 'style/FlowerPage.css' %}">
    <link rel="stylesheet" href="{% static 'style/processingPage.css' %}">
    <link rel="stylesheet" href="{% static 'style/BlogDetail.css' %}">


    <!-- animate -->
    <link rel="stylesheet" href="{% static 'style/animate.css' %}" />



    <title>Home</title>
</head>

<body>


    <!-- header -->
    <section>
        <header>

            <!-- navbar -->
                {% include "partials/_navbar.html" %}


        </header>
    </section>
    <!-- end header -->


    {% block content %}
    {% endblock content %}

    {% include "partials/_footer.html" %}
    
    {% comment %} <div class="alaki">

    </div> {% endcomment %}





    <!-- bootstrap js -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <!-- font awesome -->
    <script src="https://kit.fontawesome.com/8722263165.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/all.min.js' %}"></script>
    <!-- script -->
    <script src="{% static 'js/Homescript.js' %}"></script>
    <script src="{% static 'js/WebScript.js' %}"></script>
    <script src="{% static 'js/FlowerPage.js' %}"></script>
    <script src="{% static 'js/processingPage.js' %}"></script>



</body>

</html>

templates/partials/_navbar.html
{% load static %}

<nav>
    <div class="navbar-org">
        <div class="logo">
            <img src="{% static 'assets/logo-org.png' %}" class="img-fluid logo-img">
            اسم برند
        </div>

        <div class="navbar-items">
            <ul class="p-0 m-0">
                <li class="nav-item {% if request.path == '/' %}active{% endif %}"><a href="/" >صفحه اصلی</a></li>
                <li class="nav-item {% if request.path == '/flowers/' %}active{% endif %}"><a href="/flowers">گل ها</a></li>
                <li class="nav-item {% if request.path == '/processing/' %}active{% endif %}"><a href="/processing">تشخیص نام گل</a></li>
                <li class="nav-item"><a href="#">ارتباط با ما</a></li>
                <li class="nav-item {% if request.path == '/blog/' %}active{% endif %}"><a href="/blog">وبلاگ</a></li>
            </ul>
        </div>

        <div class="search-box d-flex">
            <form action="{% url 'flower:search' %}" class="p-0 m-0" method="GET">
                <input type="search" name="search" id="" class="m-0 search-input">
                <button type="submit" class="search-button rounded-circle mx-2">
                    <i class="fas fa-search"></i>
                </button>
            </form> 
        </div>
    </div>

    <div class="btnav">
        <div class='wrapper'>
            <input class='dot-menu__checkbox' id='dot-menu' type='checkbox'>
            <label class='dot-menu__label' for='dot-menu'>
                <span>Menu</span>
            </label>
        </div>


    </div>

</nav>